
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'gradle'

      - name: Main Build
        run: ./gradlew build check

# Upload the core API and Implementation as github artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: service-artifacts
          path: service-*/build/libs/service-*.jar
          retention-days: 7

      - name: Build AWS Lambda Deployment
        run: ./gradlew :aws-service:dist

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: AWS CDK npm init
        run: npm ci
        working-directory: aws-deploy
      - name: AWS CDK cdk deploy
        run: npm run cdk deploy simple-oidc
        working-directory: aws-deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          LAMBDA_HOSTNAME: ${{ vars.LAMBDA_HOSTNAME }}
          LOOKUP_BASENAME: ${{ vars.LOOKUP_BASENAME }}

